### ISSUE TITLE
How to generate link with title and thumbnail

### ISSUE THREAD

**Issue by Mondane** [netglue/Expressive-Prismic#7]
I have a prismic content type with a link to content on it. When I load this content type and render it with `asHtml('linkedContent')`, I get a HREF-tag to it. What I would like, is to have a nice link with a title and perhaps a thumbnail displaying the linked content.

How would I approach this? What I can think of now, is creating a group in my content type with:

* thumbnail
* title
* linkedContent

And then render the link manually using `asText` on each item.

But this seems wrong since that information belongs to the linkedContent.

Any ideas?

**Comment by gsteel** [comment]
I guess if you're rendering perhaps a list of 'Featured Links', I would normally configure a Slice or a group at Prismic to represent each featured link, so your group may look like:
```json
"links": {
    "type": "Group",
    "config": {
        "label": "Links",
        "repeat": true,
        "fields": {
            "text": {
                "type": "Text",
                "config": {
                    "label": "Link Text"
                }
            },
            "url": {
                "type": "Link",
                "config": {
                    "label": "URL",
                    "allowTargetBlank": true
                }
            },
            "title": {
                "type": "Text",
                "config": {
                    "label": "Title"
                }
            },
            "image" : {
                "type": "Image",
                "config": {
                    "constraint": {
                        "width": 500,
                        "height": 500
                    }
                }
            }
        }
    }
}
```

Then assuming you're working with the current document, you'll be able to iterate over the links and render each element to HTML in your view. I think that's pretty much what you've described… However, your link 'Fragment' will likely be a `\Prismic\Fragment\Link\DocumentLink` so you can retrieve it's ID with `$link->getId()` and then retrieve the document from the API with `$api->getById($id)` - You'll then be able to render your featured link using information from that document. Prismic does have a fetch_links option which I believe can make this easier, requiring less round trips to the Api, but I haven't worked with that yet. Hope that helps? FWIW, I normally design thing like this from the context of the linking document unless the documents I'm linking to are a very specific type.
